language: node_js
node_js:
  - "6.2"
  - "6.1"
  - "6.0"
  - "4.4"
  - "4.3"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.10"
  - "0.8"
  
after_script:
  - npm run coveralls

install:
  - npm --version
  - npm install

script:
  - ./node_modules/grunt-cli/bin/grunt build
  
sudo: false